cargo-features = ["profile-rustflags", "codegen-backend"]

[workspace]
resolver = "2"
members = [
    "div176",
    "crates/*"
]
default-members = ["div176"]

[workspace.dependencies]
axum = { version = "0.7" }
tokio = { version = "1.41", features = ["full"] }
anyhow = { version = "1.0.92" }

[profile.release]
codegen-units = 1
lto = "fat"

[profile.dev-fast]
inherits = "dev"
codegen-backend = "cranelift"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
