[package]
name = "hypertext"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
hypertext = { features = ["axum"], version = "0.5.2" }

[dev-dependencies]
pretty_assertions.workspace = true
