[package]
name = "components"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
hypertext = { path = "../hypertext/" }
serde_json.workspace = true
