[package]
name = "rsx"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
http = "1.1"
hypertext = { version = "0.5", features = ["axum"] }
