[alias]
c = ["watch", "-c", "-x", "clippy --all-targets"]
r = ["watch", "--env-file", ".env", "-c", "-x", "run --profile dev-fast"]
rr = ["watch", "--env-file", ".env", "-c", "-x", "run --release"]
t = "nextest run"
