[package]
name = "div176"
version = "0.0.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.41", features = ["full"] }
telemetry = { path = "../crates/telemetry/" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
