[package]
name = "div176"
version = "0.0.0"
edition = "2021"

[dependencies]
db = { path = "../crates/db/" }
rsx = { path = "../crates/rsx/" }
telemetry = { path = "../crates/telemetry/" }

axum = "0.7"
tokio = { version = "1.41", features = ["full"] }
