[package]
name = "div176"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
db = { path = "../crates/db/" }
rsx = { path = "../crates/rsx/" }
telemetry = { path = "../crates/telemetry/" }

axum.workspace = true
tokio.workspace = true
