[package]
name = "telemetry"
version = "0.0.0"
edition = "2021"

[dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = { version = "0.1", features = ["attributes"] }
