[package]
name = "db"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
sqlx = { version = "0.8", features = [ "sqlite", "macros", "chrono", "runtime-tokio" ] }

unreachable_macro = { path = "../unreachable_macro/" }
