name: CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-rust-env"
      - run: cargo clippy --all-targets --all-features
        env:
          RUSTFLAGS: "-Dwarnings"

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-rust-env"
      - run: cargo fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-rust-env"
      - uses: taiki-e/install-action@nextest
      - run: cargo nextest run

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-rust-env"
      - run: cargo build --release
